cmake_minimum_required(VERSION 3.10.0)
project(LB6 VERSION 0.1.0 LANGUAGES C CXX)

add_executable(Task1 
    Task1.cpp
    Counter.cpp
)
add_executable(Task2 
    Task2.cpp
    Point.cpp
)
add_executable(Task3 
    Task3.cpp
    DigitalClock.cpp
)
add_executable(Task4 
    Task4.cpp
    Student.cpp
)
add_executable(Task5 
    Task5.cpp
    SmartArray.cpp
)

